### ISSUE TITLE
fix(global): mobile view experience is not pleasant at any page

### ISSUE THREAD

**Issue by MrHumanRebel** [Project-PackX/frontend#115]

**Comment by arturfriedrich** [comment]
az nem is lesz, sok idő, ha van kedved megcsinálhatod, de szerintem felesleges

**Comment by MrHumanRebel** [comment]
Azt hittem egyszerűbb, akkor maradjon inkább csak a gépes nézet.

**Comment by arturfriedrich** [comment]
meg is kellene deisgnelni, meg sok helyen átírni, nem ér annyit
