### ISSUE TITLE
fix(style): 1920x1080 100% zoom register and login view

### ISSUE THREAD

**Issue by MrHumanRebel** [Project-PackX/frontend#121]
![image](https://github.com/Project-PackX/frontend/assets/80947401/8eb6cf03-10ae-4037-9c06-78ffe56663c9)

**Comment by arturfriedrich** [comment]
nálam jó, lezárom
<img width="1710" alt="image" src="https://github.com/Project-PackX/frontend/assets/67378210/b2948678-1436-491f-b827-b289f01adb1b">
