### ISSUE TITLE
(courier): packages view

### ISSUE THREAD

**Issue by arturfriedrich** [Project-PackX/frontend#69]
adott futárhoz tartozó összes csomag:
- gyorsgomb a státuszváltáshoz

külön táblázat a ma kiszállítandó csomagoknak

**Comment by dominikszilagyi** [comment]
POST /api/packages/statusup : Eggyel megnöveli a státuszt (JSONban "Package_ID" alapján)
GET /api/packages/courierpackages/:id : Visszaadja az 'id', mint futár ID alapján a csomagjait (jelenleg van 1-es és 2-es ID-jű futár)

**Comment by arturfriedrich** [comment]
@dominikszilagyi 
azt jól látom, hogy a GET /api/packages/courierpackages/:id nem adja vissza a csomagok státuszát? pedig az jó lenne, hogy a futár lássa a jelenlegi státusz anélkül, hogy trackelni kellene

de ugyan ez igaz a historynál, ott is jó lenne mindegyik csomaghoz odaírni, hogy melyiknek mi a státusza
