### ISSUE TITLE
feat(package): separate dates

### ISSUE THREAD

**Issue by MrHumanRebel** [Project-PackX/frontend#78]
Separate Delivery Due and Delivery Date.
Due => The interval within the package shall be delivered. 
Date => The actual delivery date.

**Comment by arturfriedrich** [comment]
@MrHumanRebel  itt mire gondolsz pontosan?

**Comment by MrHumanRebel** [comment]
Tehát a "Due" mint határidő az lenne amit az adott szolgáltatás kínál sameday,1,3,5 nap.
A tényleges dátum mint kiszállítási dátum lenne, amikor a futár rányom, hogy igen a csomagot kiszállítottam. Persze ennek mindig a határidőnél kisebbnek kell lennie, hogy határidőn belül maradjunk.
