### ISSUE TITLE
fix(api): after backend update almost every api endpoint is broken

### ISSUE THREAD

**Issue by MrHumanRebel** [Project-PackX/frontend#90]
Tried to fix and update, but was not successful.

**Comment by arturfriedrich** [comment]
@MrHumanRebel melyikre gondolsz? nekem működik az összes amit kipróbáltam

**Comment by MrHumanRebel** [comment]
Már megszereltem bocsi. #90

**Comment by arturfriedrich** [comment]
@MrHumanRebel ha valamit csinálsz azt tedd át magadra, mert így nem tudom mi az amit nekem kell megcsinálnom és mi az amit neked

**Comment by MrHumanRebel** [comment]
Ennél az egynél felejtettem el, ha megnézed a többinél átraktam. @arturfriedrich
